# Generated by Django 3.1.7 on 2021-03-12 12:14

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('squares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='duration',
            field=models.DurationField(choices=[(datetime.timedelta(days=1), '1 day'), (datetime.timedelta(days=2), '2 days'), (datetime.timedelta(days=3), '3 days'), (datetime.timedelta(days=4), '4 days'), (datetime.timedelta(days=5), '5 days'), (datetime.timedelta(days=6), '6 days'), (datetime.timedelta(days=7), '7 days')], default=datetime.timedelta(days=1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='listing',
            field=models.CharField(choices=[('l', 'lease'), ('s', 'sale')], default='l', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
